CREATE DATABASE PIZZA_SALES_ANALYSIS;
SHOW DATABASES;
USE PIZZA_SALES_ANALYSIS;
CREATE TABLE `ORDER` (
ID INT,
DATE DATE
);
ALTER TABLE `ORDER`ADD COLUMN TIME TIME AFTER DATE;
SHOW TABLES FROM PIZZA_SALES_ANALYSIS;
SELECT * FROM `ORDER`;
ALTER TABLE `ORDER` RENAME TO ORDERS;
SELECT * FROM ORDERS;
ALTER TABLE ORDERS ADD PRIMARY KEY (ID);
DESC ORDERS;