SHOW DATABASES;
create database BankingDB;
use BankingDB;
CREATE TABLE Customers
(
CustomerID INT,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100),
Phone VARCHAR(15)
);
use BankingDB;
show tables;
use BankingDB;

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100),
Phone VARCHAR(15),
AccountCreationDate Date
);
DROP TABLE CUSTOMERS;
CREATE TABLE Customers(
CustomerID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100),
Phone VARCHAR(15),
AccountCreationDate Date
);
desc customers;
CREATE TABLE ACCOUNTS (
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2)
);
DESC ACCOUNTS;
CREATE TABLE TRANSACTIONS (
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20)
);
DESC TRANSACTIONS;
CREATE TABLE BRANCHES (
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(200),
BRANCHPHONE VARCHAR(15)
);
DESC BRANCHES;
CREATE TABLE ACCOUNTBRANCHES (
ASSIGNMENTDATE date
);
SHOW TABLES;
CREATE TABLE LOANS (
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL(5,2),
STARTDATE DATE,
ENDDATE date
);
SHOW TABLES;




